USE pig_sanctuary_db;
INSERT INTO pigs(pigName, pigAge, pigGender, pigImage, pigColor, pigBio, isAdopted)
VALUES ("Christine & Carter", "Toddler", "F", "http://www.ironwoodpigs.org/images/christine-and-karter.jpg", "Spots", "We are3 year old twins! We love apples and carrots. Our coats are like mini cows!", False),
("Paisle Mae", "Toddler", "F", "http://www.ironwoodpigs.org/images/paisley-mae.jpg", "White", "I'm a 5 years old. I love running around with kids. My coat is beautiful, soft and pink", False),
("Dexter", "Toddler",  "M", "http://www.ironwoodpigs.org/images/dexter.jpg", "Brown", "I'm a 4 year old. I love laying in the shade underneath the trees. My coat is rough, but my heart is soft!", False), 
("Wilbur", "Teenager",  "M", "http://www.ironwoodpigs.org/images/wilbur.jpg", "White", "I just arrived in November of 2012 after my family lost their home and had nowhere to take me. I was scared at first and wouldn’t even go in a shelter. The people here gave me a bed and blankets until I got brave enough to go inside the pig house. They sure made me feel welcome and kept me comfortable.", False),
("Piggie Smalls", "Adult",  "M", "http://www.ironwoodpigs.org/images/piggie-smalls.jpg", "Black", "Some people claimed to have found me in the desert but I was very obese at the time. They were keeping me in a 10x10 pen. Yikes, hardly any room to move!", False),
("Daphne", "Teenager",  "F", "http://www.ironwoodpigs.org/images/cecil.jpg", "Pink", "I came here with my sister Ashley. We were both skinny and covered with ticks...yuk! After lots of vitamins, food and tick shampoo, life is great. I live with other pigs and get all the food I need. Love it!!", False),
("Karloff", "Adult",  "M", "http://www.ironwoodpigs.org/images/karloff.jpg", "Spotted", "I came to Ironwood with my brother Bert after our owners moved to a place not zoned for pigs. I had been attacked by dogs and have a huge scar on my side. I am safe and content living here.", False),
("Sue-e", "Teenager",  "F", "http://www.ironwoodpigs.org/images/sue-e.jpg", "Gray", "I came to Ironwood with my brother Bert after our owners moved to a place not zoned for pigs. I had been attacked by dogs and have a huge scar on my side. I am safe and content living here.", False)